 "use client";
import {useEffect,useMemo,useState} from "react";
type GK={concept:string;facts:string[];background:string};
type Item={id:string;source:string;title:string;url:string;published_at?:string|null;category:string;summary:string;why_important?:string;static_gk?:GK;exam_relevance:string[];verification:string};
type Screen="home"|"news"|"practice"|"tutor"|"archive"|"progress";
const cats=["All","National","Polity","Economy","Science & Technology","Environment","Defence","International","Sports","Awards & Culture","Education & Health","Telangana"];

export default function Home(){
 const [items,setItems]=useState<Item[]>([]),[cat,setCat]=useState("All"),[q,setQ]=useState(""),[status,setStatus]=useState("Connecting…"),[loading,setLoading]=useState(false),[dark,setDark]=useState(false),[screen,setScreen]=useState<Screen>("home"),[selected,setSelected]=useState<Item|null>(null),[practiceDone,setPracticeDone]=useState(false),[tutorQ,setTutorQ]=useState(""),[tutorA,setTutorA]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
 const load=async()=>{setLoading(true);setStatus("Refreshing live sources…");try{const u=new URL("/api/current-affairs",window.location.origin);u.searchParams.set("limit","200");if(q)u.searchParams.set("q",q);if(cat!=="All")u.searchParams.set("category",cat);if(from){u.searchParams.set("from_date",from);if(to)u.searchParams.set("to_date",to)}const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error();const x=await r.json();setItems(Array.isArray(x)?x:[]);setStatus("Live feed · "+(Array.isArray(x)?x.length:0)+" records")}catch{setItems([]);setStatus("Live API unavailable · no fabricated news shown")}finally{setLoading(false)}};
 useEffect(()=>{load();const id=setInterval(load,60000);return()=>clearInterval(id)},[]);
 const shown=useMemo(()=>items.filter(x=>cat==="All"||x.category===cat),[items,cat]);
 const go=(s:Screen)=>{setScreen(s);window.scrollTo({top:0,behavior:"smooth"})};
 const nav=[["home","⌂","Home"],["news","📰","News"],["practice","📝","Practice"],["tutor","🤖","Tutor"],["archive","📚","Archive"]] as const;
 return <main className={dark?"app dark":"app"}>
  <header className="top"><div className="bar"><div className="logo">EI</div><div className="brand"><b>Exam Intelligence</b><small>Current Affairs · Static GK · Exams · AI Tutor</small></div><div className="actions"><button onClick={()=>setDark(v=>!v)}>◐</button><button onClick={load} disabled={loading}>{loading?"…":"↻"}</button></div></div></header>
  {screen==="home"&&<><section className="hero"><div className="eyebrow">Daily Command Center</div><h1>Good morning, aspirant 👋</h1><p>Live-source current affairs → Static GK → exam relevance → revision.</p><p style={{fontSize:11}}>● {status} · auto-refresh every minute while app is active</p><div className="stats"><div className="stat"><b>{shown.length}</b><span>Visible stories</span></div><div className="stat"><b>{items.filter(x=>x.exam_relevance?.includes("UPSC")).length}</b><span>UPSC tagged</span></div><div className="stat"><b>{items.filter(x=>x.category==="Telangana").length}</b><span>Telangana</span></div><div className="stat"><b>Live</b><span>API mode</span></div></div></section><div className="notice">Daily edition shows recent items. Use Archive for date-specific retrieval of older news.</div><Edition q={q} setQ={setQ} cat={cat} setCat={setCat} from={from} setFrom={setFrom} to={to} setTo={setTo} load={load} loading={loading}/><NewsGrid items={shown} onOpen={setSelected}/><Learning go={go}/></>}
  {screen==="news"&&<ScreenWrap title="News"><Edition q={q} setQ={setQ} cat={cat} setCat={setCat} from={from} setFrom={setFrom} to={to} setTo={setTo} load={load} loading={loading}/><NewsGrid items={shown} onOpen={setSelected}/></ScreenWrap>}
  {screen==="practice"&&<ScreenWrap title="Prelims Practice"><div className="card"><span className="tag">Practice engine</span><h3>{practiceDone?"Session complete 🎉":"Current Affairs Practice"}</h3><p>{practiceDone?"You can restart or return to News.":"Practice will be grounded in the same live current-affairs records."}</p><button className="btn full" onClick={()=>setPracticeDone(v=>!v)}>{practiceDone?"Restart":"Start practice"}</button></div></ScreenWrap>}
  {screen==="tutor"&&<ScreenWrap title="AI Tutor"><div className="card"><span className="tag">Tutor</span><h3>Ask about your preparation</h3><input className="search" value={tutorQ} onChange={e=>setTutorQ(e.target.value)} placeholder="Ask a question…"/><button className="btn full" onClick={()=>setTutorA(tutorQ?"Question received: "+tutorQ:"Type a question first.")}>Ask Tutor</button>{tutorA&&<div className="notice" style={{marginTop:10}}>{tutorA}</div>}</div></ScreenWrap>}
  {screen==="archive"&&<ScreenWrap title="Historical Archive"><div className="card"><b>Search any date or date range</b><p>Older news is fetched on demand from the historical news index.</p><input className="search" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="search" type="date" value={to} onChange={e=>setTo(e.target.value)}/><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Optional keyword e.g. ISRO, GI tag, RBI…"/><button className="btn full" onClick={()=>{go("news");load()}}>Fetch archive</button></div><div className="grid" style={{marginTop:12}}>{["2026","2025","2024","2023","2022"].map(y=><button className="learn" key={y} onClick={()=>{setFrom(y+"-01-01");setTo(y+"-12-31");setQ("");go("news");setTimeout(load,0)}}><div className="ico">📅</div><div><b>{y}</b><small>Fetch full year</small></div><i>→</i></button>)}</div></ScreenWrap>}
  {screen==="progress"&&<ScreenWrap title="Progress"><div className="grid"><div className="card"><span className="tag">Current affairs</span><h3>{items.length} loaded</h3><p>Records currently returned by the live API.</p></div><div className="card"><span className="tag">Practice</span><h3>{practiceDone?"Completed":"Not started"}</h3></div></div></ScreenWrap>}
  {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="modalbox" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="tag">{selected.category}</span><h2>{selected.title}</h2><p>{selected.summary}</p>{selected.why_important&&<><h3>Why important</h3><p>{selected.why_important}</p></>}<h3>Static GK</h3>{selected.static_gk?<><b>{selected.static_gk.concept}</b><ul>{selected.static_gk.facts.map((f,i)=><li key={i}>{f}</li>)}</ul><p><b>Background:</b> {selected.static_gk.background}</p></>:<p>Static GK not available for this record.</p>}<div className="meta">{selected.source} · {selected.verification} · {(selected.exam_relevance||[]).join(" · ")}</div>{selected.url&&<a className="btn full" href={selected.url} target="_blank" rel="noreferrer">Open source</a>}</div></div>}
  <nav className="bottom">{nav.map(([id,icon,label])=><button key={id} className={screen===id?"active":""} onClick={()=>go(id)}><span>{icon}</span><span>{label}</span></button>)}<button onClick={()=>go("progress")}><span>📊</span><span>Progress</span></button></nav>
 </main>
}

function Edition({q,setQ,cat,setCat,from,setFrom,to,setTo,load,loading}:{q:string;setQ:(x:string)=>void;cat:string;setCat:(x:string)=>void;from:string;setFrom:(x:string)=>void;to:string;setTo:(x:string)=>void;load:()=>void;loading:boolean}){return <section className="section"><div className="head"><h2>{from?"Archive results":"Today’s edition"}</h2><button onClick={load}>{loading?"Refreshing…":"Refresh"}</button></div><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search current affairs…"/><div className="dateRow"><input className="search" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="search" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div className="chips" style={{marginTop:9}}>{cats.map(c=><button className={cat===c?"chip active":"chip"} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div></section>}

function ScreenWrap({title,children}:{title:string;children:React.ReactNode}){return <section className="section" style={{paddingBottom:90}}><div className="head"><h2>{title}</h2></div>{children}</section>}
function NewsGrid({items,onOpen}:{items:Item[];onOpen:(x:Item)=>void}){return <section className="section"><div className="head"><h2>Current affairs</h2><span style={{fontSize:10,color:"#667085"}}>{items.length} results</span></div><div className="grid">{items.length===0?<div className="card"><h3>No records found</h3><p>Try Refresh, another category, a keyword, or a historical date range.</p></div>:items.map(x=><article className="card" key={x.id}><span className="tag">{x.category}</span><h3>{x.title}</h3><p>{x.summary}</p><div className="meta">{x.source} · {x.verification} · {(x.exam_relevance||[]).join(" · ")}</div><button className="btn full" onClick={()=>onOpen(x)}>Read + Static GK</button></article>)}</div></section>}
function Learning({go}:{go:(s:Screen)=>void}){return <section className="section"><div className="head"><h2>Learning</h2></div><div className="grid"><button className="learn" onClick={()=>go("practice")}><div className="ico">📝</div><div><b>Prelims Practice</b><small>Grounded questions</small></div><i>→</i></button><button className="learn" onClick={()=>go("tutor")}><div className="ico">🤖</div><div><b>AI Tutor</b><small>Teach → check → retest</small></div><i>→</i></button><button className="learn" onClick={()=>go("archive")}><div className="ico">📚</div><div><b>Archive</b><small>Year → month → date</small></div><i>→</i></button><button className="learn" onClick={()=>go("progress")}><div className="ico">📊</div><div><b>Progress</b><small>Session progress</small></div><i>→</i></button></div></section>}
