"use client";
import {useEffect,useMemo,useState} from "react";

type Item={id:string;source:string;title:string;url:string;published_at?:string|null;category:string;summary:string;exam_relevance:string[];verification:string};
type Screen="home"|"news"|"practice"|"tutor"|"archive"|"progress";
const cats=["All","National","Polity","Economy","Science & Technology","Environment","Defence","International","Sports","Telangana"];

export default function Home(){
 const [items,setItems]=useState<Item[]>([]),[cat,setCat]=useState("All"),[q,setQ]=useState(""),[status,setStatus]=useState("Connecting…"),[loading,setLoading]=useState(false),[dark,setDark]=useState(false),[screen,setScreen]=useState<Screen>("home"),[selected,setSelected]=useState<Item|null>(null),[practiceDone,setPracticeDone]=useState(false),[tutorQ,setTutorQ]=useState(""),[tutorA,setTutorA]=useState("");
 const load=async()=>{setLoading(true);setStatus("Refreshing live source feed…");try{const r=await fetch("/api/current-affairs?limit=100",{cache:"no-store"});if(!r.ok)throw new Error();const x=await r.json();setItems(Array.isArray(x)?x:[]);setStatus("Live source feed · "+(Array.isArray(x)?x.length:0)+" items")}catch{setItems([]);setStatus("Live API unavailable · no fabricated news shown")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>items.filter(x=>(cat==="All"||x.category===cat)&&(!q||(x.title+" "+x.summary+" "+x.source).toLowerCase().includes(q.toLowerCase()))),[items,cat,q]);
 const go=(s:Screen)=>{setScreen(s);window.scrollTo({top:0,behavior:"smooth"})};
 const nav=[["home","⌂","Home"],["news","📰","News"],["practice","📝","Practice"],["tutor","🤖","Tutor"],["archive","📚","Archive"]] as const;
 return <main className={dark?"app dark":"app"}>
  <header className="top"><div className="bar"><div className="logo">EI</div><div className="brand"><b>Exam Intelligence</b><small>Current Affairs · Exams · AI Tutor</small></div><div className="actions"><button onClick={()=>setDark(v=>!v)}>◐</button><button onClick={load} disabled={loading}>{loading?"…":"↻"}</button></div></div></header>
  {screen==="home"&&<><section className="hero"><div className="eyebrow">Daily Command Center</div><h1>Good morning, aspirant 👋</h1><p>Live-source current affairs → verification → exam relevance → practice.</p><p style={{fontSize:11}}>● {status}</p><div className="stats"><div className="stat"><b>{shown.length}</b><span>Visible stories</span></div><div className="stat"><b>{items.filter(x=>x.exam_relevance?.includes("UPSC")).length}</b><span>UPSC tagged</span></div><div className="stat"><b>{items.filter(x=>x.category==="Telangana").length}</b><span>Telangana</span></div><div className="stat"><b>Live</b><span>API mode</span></div></div></section><div className="notice">No fabricated “today” news is shown. Only data returned by the live API appears here.</div><Edition q={q} setQ={setQ} cat={cat} setCat={setCat} load={load} loading={loading}/><NewsGrid items={shown} onOpen={setSelected}/><Learning go={go}/></>}
  {screen==="news"&&<ScreenWrap title="News"><Edition q={q} setQ={setQ} cat={cat} setCat={setCat} load={load} loading={loading}/><NewsGrid items={shown} onOpen={setSelected}/></ScreenWrap>}
  {screen==="practice"&&<ScreenWrap title="Prelims Practice"><div className="card"><span className="tag">Practice engine</span><h3>{practiceDone?"Session complete 🎉":"Current Affairs Practice"}</h3><p>{practiceDone?"You can restart or return to News.":"The practice interface is active. Verified question generation will use the backend question service when connected."}</p><button className="btn full" onClick={()=>setPracticeDone(v=>!v)}>{practiceDone?"Restart":"Start practice"}</button></div></ScreenWrap>}
  {screen==="tutor"&&<ScreenWrap title="AI Tutor"><div className="card"><span className="tag">Tutor</span><h3>Ask about your preparation</h3><p>The tutor interface is active. Live AI answers will come from the backend tutor service when connected.</p><input className="search" value={tutorQ} onChange={e=>setTutorQ(e.target.value)} placeholder="Ask a question…"/><button className="btn full" onClick={()=>setTutorA(tutorQ?"Question received: "+tutorQ:"Type a question first.")}>Ask Tutor</button>{tutorA&&<div className="notice" style={{marginTop:10}}>{tutorA}</div>}</div></ScreenWrap>}
  {screen==="archive"&&<ScreenWrap title="Historical Archive"><div className="grid">{["2026","2025","2024","2023","2022"].map(y=><button className="learn" key={y} onClick={()=>{setQ(y);go("news")}}><div className="ico">📅</div><div><b>{y}</b><small>Year archive</small></div><i>→</i></button>)}</div><div className="notice" style={{marginTop:12}}>Choose a year to search the archive index.</div></ScreenWrap>}
  {screen==="progress"&&<ScreenWrap title="Progress"><div className="grid"><div className="card"><span className="tag">Current affairs</span><h3>{items.length} live items</h3><p>Records currently returned by the source API.</p></div><div className="card"><span className="tag">Practice</span><h3>{practiceDone?"Completed":"Not started"}</h3><p>Your current practice session.</p></div></div></ScreenWrap>}
  {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="modalbox" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="tag">{selected.category}</span><h2>{selected.title}</h2><p>{selected.summary}</p><div className="meta">{selected.source} · {selected.verification}</div>{selected.url&&<a className="btn full" href={selected.url} target="_blank" rel="noreferrer">Open primary source</a>}</div></div>}
  <nav className="bottom">{nav.map(([id,icon,label])=><button key={id} className={screen===id?"active":""} onClick={()=>go(id)}><span>{icon}</span><span>{label}</span></button>)}<button onClick={()=>go("progress")}><span>📊</span><span>Progress</span></button></nav>
 </main>
}

function Edition({q,setQ,cat,setCat,load,loading}:{q:string;setQ:(x:string)=>void;cat:string;setCat:(x:string)=>void;load:()=>void;loading:boolean}){return <section className="section"><div className="head"><h2>Today’s edition</h2><button onClick={load}>{loading?"Refreshing…":"Refresh"}</button></div><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search current affairs…"/><div className="chips" style={{marginTop:9}}>{cats.map(c=><button className={cat===c?"chip active":"chip"} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div></section>}

function ScreenWrap({title,children}:{title:string;children:React.ReactNode}){return <section className="section" style={{paddingBottom:90}}><div className="head"><h2>{title}</h2></div>{children}</section>}

function NewsGrid({items,onOpen}:{items:Item[];onOpen:(x:Item)=>void}){return <section className="section"><div className="head"><h2>Current affairs</h2><span style={{fontSize:10,color:"#667085"}}>{items.length} results</span></div><div className="grid">{items.length===0?<div className="card"><h3>No live articles available</h3><p>The API returned no current-affairs records. Refresh after the source service is healthy. The app will not invent news.</p></div>:items.map(x=><article className="card" key={x.id}><span className="tag">{x.category}</span><h3>{x.title}</h3><p>{x.summary}</p><div className="meta">{x.source} · {x.verification} · {(x.exam_relevance||[]).join(" · ")}</div><button className="btn full" onClick={()=>onOpen(x)}>Read article</button></article>)}</div></section>}

function Learning({go}:{go:(s:Screen)=>void}){return <section className="section"><div className="head"><h2>Learning</h2></div><div className="grid"><button className="learn" onClick={()=>go("practice")}><div className="ico">📝</div><div><b>Prelims Practice</b><small>Grounded questions</small></div><i>→</i></button><button className="learn" onClick={()=>go("tutor")}><div className="ico">🤖</div><div><b>AI Tutor</b><small>Teach → check → retest</small></div><i>→</i></button><button className="learn" onClick={()=>go("archive")}><div className="ico">📚</div><div><b>Archive</b><small>Year → month → date</small></div><i>→</i></button><button className="learn" onClick={()=>go("progress")}><div className="ico">📊</div><div><b>Progress</b><small>Session progress</small></div><i>→</i></button></div></section>}
